image: docker:24.0.7

stages:
  - build
  - deploy

# ──────── BUILD JOBS ────────

build-auth-service-job:
  stage: build
  tags:
    - prod
  script:
    - docker build -t chatflow-service -f Backend/ChatFlow/Dockerfile Backend/ChatFlow

# ──────── DEPLOY JOB ────────

deploy-job:
  stage: deploy
  tags:
    - prod
  script:
    - docker compose down
    - docker compose build --no-cache
    - docker compose up -d --force-recreate