image: docker:24.0.7

stages:
  - build
  - deploy

# ──────── BUILD JOBS ────────

build-chatflow-service-job:
  stage: build
  tags:
    - chatFlow
  script:
    - docker build -t chatflow-service -f Backend/ChatFlow/Dockerfile Backend/ChatFlow
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "development/dev"'

# ──────── DEPLOY JOB ────────

deploy-job:
  stage: deploy
  tags:
    - chatFlow
  script:
    - export Vault__Address=$VAULT_ADDR
    - export Vault__RoleId=$VAULT_ROLE_ID
    - export Vault__SecretId=$VAULT_SECRET_ID
      
    - docker compose down
    - docker compose build --no-cache
    - docker compose up -d --force-recreate
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "development/dev"'
