version: '3.8'

networks:
  net:
    
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf:ro
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem:ro
    depends_on:
      - chat-flow
    networks:
      - net
        
  nginx-exporter:
    build: Dockerfile.nginx-exporter
    volumes:
      - nginx_log_volume:/var/log/nginx/
    
  chat-flow:
    image: chatflow-service:latest
    restart: always
    networks:
      - net